{
  "taskDefinition": {
    "family": "hello-world",
    "containerDefinitions": [
      {
        "name": "user-management-container",
        "image": "569297910765.dkr.ecr.us-east-2.amazonaws.com/user-management-repository",
        "cpu": 100,
        "portMappings": [
          {
            "protocol": "tcp",
            "containerPort": 80,
            "hostPort": 80
          }
        ],
        "memory": 128,
        "essential": true
      }
    ]
  }
}
